### PR TITLE
Evolution: allow callback funcs to take in Hamiltonian

### PR DESCRIPTION
**Pull request by adamcallison**
- convenient to use solved system in callbacks
- if hamiltonian is time-dependent, it will be cached
  and can be used for free by callbacks

Some repeated code in _setup_callbacks factored out in the process. Existing tests extended to cover these changes.

### CODE REVIEW

**Comment by jcmgray** [comment]
Hey Adam, sorry just very busy with non-work stuff the next few days but this looks nice and I'll try and get to it soon.

Just one brief comment is that python has the `inspect` module for working out how many arguments a function takes - might simplify things?

**Comment by adamcallison** [comment]
Hi, Johnnie - no rush, good luck with the next few days :)

I considered going via `inspect`, but I ultimately decided on `try except` because I didn't want to cause problems for more general callables that `inspect` might not like. Are you concerned that my approach might be slowed down the `try except` block?

I will leave this PR as is for now, happy to pick this discussion back up when things settle down for you :)

**Comment by jcmgray** [comment]
Hey Adam, so after [much wrestling](https://github.com/jcmgray/quimb/commits/develop) I seem to have brought quimb+tests+travis into harmony again. If you are still interested in this, could you rebase onto/merge the new changes?

**Comment by adamcallison** [comment]
> Hey Adam, so after [much wrestling](https://github.com/jcmgray/quimb/commits/develop) I seem to have brought quimb+tests+travis into harmony again. If you are still interested in this, could you rebase onto/merge the new changes?

Hi Johnnie, hope all is well. Rebase done (plus an extra commit to make it pep8 compliant)

**Comment by jcmgray** [comment]
OK, finally got round to reviewing this, all looks good! Thanks for the PEP8 updates and another all round good and thorough pull request.

**Pull request merged**
